open Types
open State

(* [get_move s p strat] returns the [command] generated by the AI
   player [p] for the current state [s] which operates according
   to startegy [strat].*)
val get_move : state -> player -> strategy -> command
